name: Deploy Azure GPU Robotics VM


on:
workflow_dispatch:


permissions:
id-token: write
contents: read


jobs:
deploy:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4


- uses: azure/login@v2
with:
client-id: ${{ secrets.AZURE_CLIENT_ID }}
tenant-id: ${{ secrets.AZURE_TENANT_ID }}
subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


- uses: hashicorp/setup-terraform@v3


- run: terraform init
working-directory: terraform


- run: terraform apply -auto-approve
working-directory: terraform